### ISSUE TITLE
dev-vcs/gitkraken-bin: missing libgnome-keyring dependency

### ISSUE THREAD

**Issue by reagentoo** [Keepco/gentoo-overlay-seadep#16]
```
$ /usr/bin/gitkraken
Node started time: 1502714399544
libgnome-keyring.so.0: Ð½ÐµÐ²Ð¾Ð·Ð¼Ð¾Ð¶Ð½Ð¾ Ð¾ÑÐºÑÑÑÑ ÑÐ°Ð·Ð´ÐµÐ»ÑÐµÐ¼ÑÐ¹ Ð¾Ð±ÑÐµÐºÑÐ½ÑÐ¹ ÑÐ°Ð¹Ð»: ÐÐµÑ ÑÐ°ÐºÐ¾Ð³Ð¾ ÑÐ°Ð¹Ð»Ð° Ð¸Ð»Ð¸ ÐºÐ°ÑÐ°Ð»Ð¾Ð³Ð°
Error: libgnome-keyring.so.0: Ð½ÐµÐ²Ð¾Ð·Ð¼Ð¾Ð¶Ð½Ð¾ Ð¾ÑÐºÑÑÑÑ ÑÐ°Ð·Ð´ÐµÐ»ÑÐµÐ¼ÑÐ¹ Ð¾Ð±ÑÐµÐºÑÐ½ÑÐ¹ ÑÐ°Ð¹Ð»: ÐÐµÑ ÑÐ°ÐºÐ¾Ð³Ð¾ ÑÐ°Ð¹Ð»Ð° Ð¸Ð»Ð¸ ÐºÐ°ÑÐ°Ð»Ð¾Ð³Ð°
    at Error (native)
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:158:20)
    at Object.Module._extensions..node (module.js:568:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:169:18)
    at Module.load (module.js:456:32)
    at tryModuleLoad (module.js:415:12)
    at Function.Module._load (module.js:407:3)
    at Module.require (module.js:466:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/opt/gitkraken-bin/resources/app.asar/node_modules/keytar/lib/keytar.js:4:12)
    at Object.<anonymous> (/opt/gitkraken-bin/resources/app.asar/node_modules/keytar/lib/keytar.js:58:4)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:456:32)
    at tryModuleLoad (module.js:415:12)
    at Function.Module._load (module.js:407:3)
    at Module.require (module.js:466:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/opt/gitkraken-bin/resources/app.asar/src/appBootstrap/upgradeScripts/versionScripts/v1_5_0.js:10:16)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:456:32)
    at tryModuleLoad (module.js:415:12)
    at Function.Module._load (module.js:407:3)
    at Module.require (module.js:466:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/opt/gitkraken-bin/resources/app.asar/src/appBootstrap/upgradeScripts/versionScripts/index.js:5:28)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:456:32)
    at tryModuleLoad (module.js:415:12)
    at Function.Module._load (module.js:407:3)
    at Module.require (module.js:466:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/opt/gitkraken-bin/resources/app.asar/src/appBootstrap/upgradeScripts/index.js:7:24)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:456:32)
    at tryModuleLoad (module.js:415:12)
    at Function.Module._load (module.js:407:3)
    at Module.require (module.js:466:17)
    at require (internal/module.js:20:19)
    at EventEmitter.module.exports.app.on (/opt/gitkraken-bin/resources/app.asar/src/appBootstrap/main.js:174:5)
    at emitOne (events.js:101:20)
    at EventEmitter.emit (events.js:188:7)
```

**Comment by reagentoo** [comment]
Also http://i.imgur.com/7BI06g5.png

**Comment by Cogitri** [comment]
Fonts not rendering properly seems to be a more widespread problem : https://github.com/Azd325/gitkraken/issues/45
Guess we could either switch over to "building" gitkraken, or wait for 2.8

Thanks for reporting :)
