### ISSUE TITLE
x11-terms/hyper-1.3.3 failed to build

### ISSUE THREAD

**Issue by Cynede** [Keepco/gentoo-overlay-seadep#9]
```
Hash: 3354e5be6fcbdea46475
Version: webpack 2.2.1
Time: 3426ms
           Asset     Size  Chunks                    Chunk Names
       bundle.js  1.62 MB       0  [emitted]  [big]  main
   bundle.js.map  2.04 MB       0  [emitted]         main
assets/icons.svg  3.34 kB          [emitted]         
   [5] ./~/react/react.js 56 bytes {0} [built]
   [6] ./lib/utils/plugins.js 9.34 kB {0} [built]
  [18] ./lib/rpc.js 57 bytes {0} [built]
  [30] ./lib/actions/sessions.js 3.23 kB {0} [built]
  [31] ./lib/actions/term-groups.js 4.08 kB {0} [built]
  [72] ./lib/actions/notifications.js 347 bytes {0} [built]
  [73] ./lib/actions/ui.js 5.35 kB {0} [built]
  [74] ./lib/actions/updater.js 355 bytes {0} [built]
 [129] ./lib/actions/config.js 245 bytes {0} [built]
 [130] ./lib/actions/index.js 205 bytes {0} [built]
 [132] ./lib/store/configure-store.js 273 bytes {0} [built]
 [133] ./lib/utils/config.js 346 bytes {0} [built]
 [134] ./~/react-deep-force-update/lib/index.js 1.45 kB {0} [built]
 [135] ./~/react-dom/index.js 63 bytes {0} [built]
 [308] ./lib/index.js 3.98 kB {0} [built]
    + 294 hidden modules
Rebuilding native production dependencies for linux:x64
⚠️  Packaging using asar archive is disabled — it is strongly not recommended.
Please enable asar and use asarUnpack to unpack files that must be externally available.                                                                
Packaging for linux x64 using electron 1.4.16 to dist/linux-unpacked
Building AppImage for arch x64
Error: Exit code: 127. Command failed: /var/tmp/p378d4474adf3691a6618139e2d617382f3360fe9b139cd68d6f8473bc120dd07 (sha256 hash) -joliet on -volid AppImage -dev /var/tmp/portage/x11-terms/hyper-1.3.3/work/hyper-1.3.3/dist/hyper-1.3.2-x86_64.AppImage -padding 0 -map /var/tmp/portage/x11-terms/hyper-1.3.3/work/hyper-1.3.3/dist/linux-unpacked /usr/bin -map /var/tmp/portage/x11-terms/hyper-1.3.3/work/hyper-1.3.3/node_modules/electron-builder/templates/linux/AppRun.sh /AppRun -map /var/tmp/portage/x11-terms/hyper-1.3.3/temp/electron-builder-fHZr2E/0-4-Hyper.desktop /hyper.desktop -map /var/tmp/portage/x11-terms/hyper-1.3.3/temp/electron-builder-fHZr2E/0-3-linux.iconset/icon_16x16x32.png /usr/share/icons/default/16x16/apps/hyper.png -map /var/tmp/portage/x11-terms/hyper-1.3.3/temp/electron-builder-fHZr2E/0-3-linux.iconset/icon_24x24x32.png /usr/share/icons/default/24x24/apps/hyper.png -map /var/tmp/portage/x11-terms/hyper-1.3.3/temp/electron-builder-fHZr2E/0-3-linux.iconset/icon_32x32x32.png /usr/share/icons/default/32x32/apps/hyper.png -map /var/tmp/portage/x11-terms/hyper-1.3.3/temp/electron-builder-fHZr2E/0-3-linux.iconset/icon_48x48x32.png /usr/share/icons/default/48x48/apps/hyper.png -map /var/tmp/portage/x11-terms/hyper-1.3.3/temp/electron-builder-fHZr2E/0-3-linux.iconset/icon_64x64x32.png /usr/share/icons/default/64x64/apps/hyper.png -map /var/tmp/portage/x11-terms/hyper-1.3.3/temp/electron-builder-fHZr2E/0-3-linux.iconset/icon_96x96x32.png /usr/share/icons/default/96x96/apps/hyper.png -map /var/tmp/portage/x11-terms/hyper-1.3.3/temp/electron-builder-fHZr2E/0-3-linux.iconset/icon_128x128x32.png /usr/share/icons/default/128x128/apps/hyper.png -map /var/tmp/portage/x11-terms/hyper-1.3.3/temp/electron-builder-fHZr2E/0-3-linux.iconset/icon_256x256x32.png /usr/share/icons/default/256x256/apps/hyper.png -map /var/tmp/portage/x11-terms/hyper-1.3.3/temp/electron-builder-fHZr2E/0-3-linux.iconset/icon_512x512x32.png /usr/share/icons/default/512x512/apps/hyper.png -map /var/tmp/portage/x11-terms/hyper-1.3.3/temp/electron-builder-fHZr2E/0-3-linux.iconset/icon_256x256x32.png /.DirIcon -chown_r 0 / -- -zisofs level=9:block_size=128k:by_magic=off set_filter_r --zisofs /                                                                                       
/var/tmp/portage/x11-terms/hyper-1.3.3/homedir/.cache/electron-builder/AppImage/AppImage-09-07-16-linux/xorriso: error while loading shared libraries: libreadline.so.6: cannot open shared object file: No such file or directory                                                                              

/var/tmp/portage/x11-terms/hyper-1.3.3/homedir/.cache/electron-builder/AppImage/AppImage-09-07-16-linux/xorriso: error while loading shared libraries: libreadline.so.6: cannot open shared object file: No such file or directory                                                                              

    at /var/tmp/portage/x11-terms/hyper-1.3.3/work/hyper-1.3.3/node_modules/electron-builder-util/src/util.ts:75:16                                     
    at ChildProcess.exithandler (child_process.js:211:5)                                                                                                
    at emitTwo (events.js:106:13)                                                                                                                       
    at ChildProcess.emit (events.js:191:7)                                                                                                              
    at maybeClose (internal/child_process.js:886:16)                                                                                                    
    at Socket.<anonymous> (internal/child_process.js:342:11)                                                                                            
    at emitOne (events.js:96:13)                                                                                                                        
    at Socket.emit (events.js:188:7)                                                                                                                    
    at Pipe._handle.close [as _onclose] (net.js:497:12)                                                                                                 
From previous event:                                                                                                                                    
    at exec (/var/tmp/portage/x11-terms/hyper-1.3.3/work/hyper-1.3.3/node_modules/electron-builder-util/src/util.ts:53:3)                               
    at /var/tmp/portage/x11-terms/hyper-1.3.3/work/hyper-1.3.3/node_modules/electron-builder/src/targets/appImage.ts:79:11                              
    at next (native)                                                                                                                                    
From previous event:                                                                                                                                    
    at AppImageTarget.build (/var/tmp/portage/x11-terms/hyper-1.3.3/work/hyper-1.3.3/node_modules/electron-builder/out/targets/appImage.js:142:11)      
    at postAsyncTasks.push.default.map.it (/var/tmp/portage/x11-terms/hyper-1.3.3/work/hyper-1.3.3/node_modules/electron-builder/src/platformPackager.ts:103:85)                                                                                                                                                
From previous event:                                                                                                                                    
    at LinuxPackager.packageInDistributableFormat (/var/tmp/portage/x11-terms/hyper-1.3.3/work/hyper-1.3.3/node_modules/electron-builder/src/platformPackager.ts:103:41)                                                                                                                                        
    at /var/tmp/portage/x11-terms/hyper-1.3.3/work/hyper-1.3.3/node_modules/electron-builder/src/platformPackager.ts:99:10                              
From previous event:                                                                                                                                    
    at LinuxPackager.pack (/var/tmp/portage/x11-terms/hyper-1.3.3/work/hyper-1.3.3/node_modules/electron-builder/out/platformPackager.js:160:11)        
    at /var/tmp/portage/x11-terms/hyper-1.3.3/work/hyper-1.3.3/node_modules/electron-builder/src/packager.ts:229:22                                     
From previous event:                                                                                                                                    
    at Packager.doBuild (/var/tmp/portage/x11-terms/hyper-1.3.3/work/hyper-1.3.3/node_modules/electron-builder/out/packager.js:350:11)                  
    at /var/tmp/portage/x11-terms/hyper-1.3.3/work/hyper-1.3.3/node_modules/electron-builder/src/packager.ts:157:38                                     
    at next (native)                                                                                                                                    
    at runCallback (timers.js:672:20)                                                                                                                   
    at tryOnImmediate (timers.js:645:5)                                                                                                                 
    at processImmediate [as _immediateCallback] (timers.js:617:5)                                                                                       
From previous event:                                                                                                                                    
    at Packager.build (/var/tmp/portage/x11-terms/hyper-1.3.3/work/hyper-1.3.3/node_modules/electron-builder/out/packager.js:256:11)                    
    at /var/tmp/portage/x11-terms/hyper-1.3.3/work/hyper-1.3.3/node_modules/electron-builder/src/builder.ts:217:65                                      
    at next (native)                                                                                                                                    
From previous event:                                                                                                                                    
    at build (/var/tmp/portage/x11-terms/hyper-1.3.3/work/hyper-1.3.3/node_modules/electron-builder/out/builder.js:71:21)                               
    at Object.<anonymous> (/var/tmp/portage/x11-terms/hyper-1.3.3/work/hyper-1.3.3/node_modules/electron-builder/out/cli/build-cli.js:71:41)            
    at Module._compile (module.js:570:32)                                                                                                               
    at Object.Module._extensions..js (module.js:579:10)                                                                                                 
    at Module.load (module.js:487:32)                                                                                                                   
    at tryModuleLoad (module.js:446:12)                                                                                                                 
    at Function.Module._load (module.js:438:3)                                                                                                          
    at Module.runMain (module.js:604:10)                                                                                                                
    at run (bootstrap_node.js:390:7)                                                                                                                    
    at startup (bootstrap_node.js:150:9)                                                                                                                
    at bootstrap_node.js:505:3                                                                                                                          

npm ERR! Linux 4.11.0-gentoo
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "run" "dist"
npm ERR! node v6.10.3
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! @ dist: `npm run build && cross-env BABEL_ENV=production babel --out-file app/dist/bundle.js --no-comments --minified app/dist/bundle.js && build`
npm ERR! Exit status 255
npm ERR! 
npm ERR! Failed at the @ dist script 'npm run build && cross-env BABEL_ENV=production babel --out-file app/dist/bundle.js --no-comments --minified app/dist/bundle.js && build'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the  package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run build && cross-env BABEL_ENV=production babel --out-file app/dist/bundle.js --no-comments --minified app/dist/bundle.js && build
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs 
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls 
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /var/tmp/portage/x11-terms/hyper-1.3.3/work/hyper-1.3.3/npm-debug.log

```

**Comment by Cogitri** [comment]
I guess readline is missing, do you use libedit? If so, could you try emerging readline and try emerging hyper again?

**Comment by Cynede** [comment]
@Keepco readline 7.0 p3 is installed

**Comment by Cogitri** [comment]
Weird, I just emerged readline-7.0_p3 and I'm still able to build Hyper. Could you compile hyper ( `ebuild /usr/local/seadep/x11-terms/hyper/hyper-1.3.3.ebuild compile` ) and issue `ldd /var/tmp/portage/x11-terms/hyper-1.3.3/homedir/.cache/electron-builder/AppImage/AppImage-09-07-16-linux/xorriso`? libreadline.so.6 should link to /lib64/libreadline.so.6

**Comment by Cynede** [comment]
@Keepco can't provide more information for now, I will reopen this issue if I will get back to it, or feel free to reopen if you want to dig more there by yourself.

**Comment by Cogitri** [comment]
Well, I can't reproduce it on any of my machines, just reopen it when you encounter it again ( or open a PR if you find the solution! ;)
